MODULE ALIB

  IMPLICIT NONE

CONTAINS

  INTEGER FUNCTION FOO(N)
    INTEGER, INTENT(IN) :: N
    FOO = N + 2
  END FUNCTION FOO

  SUBROUTINE FOO2(N, M)
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(OUT) :: M
    M = N + 2
  END SUBROUTINE FOO2

END MODULE ALIB
